/****** Object:  Table [dbo].[NPC]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[NPC](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[Class] [int] NULL,
	[Race] [int] NULL,
	[Appearance] [varchar](2000) NULL,
 CONSTRAINT [PK_NPC] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[NPC]  WITH CHECK ADD  CONSTRAINT [FK_NPC_Class] FOREIGN KEY([Class])
REFERENCES [dbo].[Class] ([Id])
ALTER TABLE [dbo].[NPC] CHECK CONSTRAINT [FK_NPC_Class]
ALTER TABLE [dbo].[NPC]  WITH CHECK ADD  CONSTRAINT [FK_NPC_Race] FOREIGN KEY([Race])
REFERENCES [dbo].[Race] ([Id])
ALTER TABLE [dbo].[NPC] CHECK CONSTRAINT [FK_NPC_Race]
